# Redis server information
redis_server: 127.0.0.1
redis_port: 6379

# Run worker as daemon
worker_daemons: 
# Worker PID
worker_daemon_pid: /var/harvester.pid

# Queue for incoming messages
subscribe_queue: 'mine'
# Queue for outgoing messages
publish_queue: 'package'

# Protocol specific constraints
protocol:
    lj:
        timeout: 60
        retry_attemps: 5

